apiVersion: apps/v1
kind: Deployment
metadata:
  name: prove-web
  namespace: prove
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prove-web
  template:
    metadata:
      labels:
        app: prove-web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: prove-web
          image: ghcr.io/team-peenoo/prove:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
