apiVersion: v1
kind: Service
metadata:
  name: prove-web-svc
  namespace: prove
spec:
  selector:
    app: prove-web
  ports:
    - name: http
      port: 12568       # 호스트에서 klipper-lb가 바인딩하는 포트 (NGINX Proxy Manager가 바라보는 포트)
      targetPort: 80    # 컨테이너 내부 nginx 포트
  type: LoadBalancer
