apiVersion: v1
kind: Service
metadata:
  name: prove-web-svc
  namespace: prove
spec:
  selector:
    app: prove-web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
